spring:
  security:
    user:
      name: admin
      password: admin123
common:
  commonAppName: "secureChatBackend"
generalInfo:
  appInfo:
    excludedUrls: "/auth/register,/auth/login,/public,/error,/eureka"
    constInfo:
      secret: "secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret"
      expiration: 3600
